packages:
  - e2e
  - apps/**
  - packages/**

catalog:
  '@noeldemartin/solid-utils': next
  '@noeldemartin/utils': next
  '@tailwindcss/vite': ^4.1.18
  '@vitejs/plugin-vue': ^6.0.4
  ai: ^6.0.100
  soukai-bis: next
  tailwindcss: ^4.1.18
  typescript: ~5.9.3
  vite: beta
  vue: ^3.5.28
  vue-tsc: ^3.2.4
  zod: ^4.3.6

overrides:
  '@vue/compat': beta
  '@vue/compiler-core': beta
  '@vue/compiler-dom': beta
  '@vue/compiler-sfc': beta
  '@vue/compiler-ssr': beta
  '@vue/compiler-vapor': beta
  '@vue/reactivity': beta
  '@vue/runtime-core': beta
  '@vue/runtime-dom': beta
  '@vue/runtime-vapor': beta
  '@vue/server-renderer': beta
  '@vue/shared': beta
  vue: beta

patchedDependencies:
  '@inrupt/solid-client-authn-core': patches/@inrupt__solid-client-authn-core.patch
  '@inrupt/solid-client-authn-node': patches/@inrupt__solid-client-authn-node.patch

peerDependencyRules:
  allowAny:
    - vue
